services:
  - type: worker
    name: telegram-bot
    env: python
    pythonVersion: 3.13
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoRestart: true
    numInstances: 1  # Гарантирует один экземпляр
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
